### ISSUE TITLE
Setting up Kanban board

### ISSUE THREAD

**Issue by haliljon** [haliljon/Space-travelers#25]
## In this issue we created new Kanban board

Here is the link for the project: [Project](https://github.com/haliljon/Space-travelers/projects/1 )

There are 2 members in our group

**Comment by AmaduKamara** [comment]
# Status: Approved 🟢 🟢 🟢

Hi Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

✅ Set up the Kanban board correctly 👍🏽
✅ All tasks are fairly shared and assigned correctly 👍🏽
✅ Kanban Board has all required columns 👍🏽
✅ Each task has points, a title, an assignee, and a description. 👍🏽

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
